/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.transversal.vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import proyecto.transversal.accesoADatos.Usuario_Data;
import proyecto.transversal.entidades.Usuario;

/**
 *
 * @author ferben007
 */
public class CambioContrase extends javax.swing.JPanel {
        public Login login = new Login();
        private Usuario_Data ud = null;
        //private Usuario carga = null;
        private String nombreUsuario = null;
    /**
     * Creates new form CambioContrase
     */
    public CambioContrase() {
        initComponents();
        jPass.setVisible(false);
        jPassRepe.setVisible(false);
        labelContraRepe.setVisible(false);
        labelContra.setVisible(false);
        panelCambio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCambioContrase = new javax.swing.JPanel();
        jtUsuario = new javax.swing.JTextField();
        jPass = new javax.swing.JPasswordField();
        jPassRepe = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        labelPresentacion = new javax.swing.JLabel();
        panelIngresar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelContraRepe = new javax.swing.JLabel();
        labelContra = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();
        panelCambio = new javax.swing.JPanel();
        labelCambio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelCerrar = new javax.swing.JPanel();
        labelCerrar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));

        panelCambioContrase.setBackground(new java.awt.Color(153, 153, 255));
        panelCambioContrase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtUsuario.setForeground(java.awt.Color.gray);
        jtUsuario.setText("Ingrese su Usuario");
        jtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtUsuarioMousePressed(evt);
            }
        });
        panelCambioContrase.add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 120, 220, -1));

        jPass.setForeground(java.awt.Color.gray);
        jPass.setText("****");
        jPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPassMousePressed(evt);
            }
        });
        jPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassKeyTyped(evt);
            }
        });
        panelCambioContrase.add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 220, -1));

        jPassRepe.setForeground(java.awt.Color.gray);
        jPassRepe.setText("****");
        jPassRepe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPassRepeMousePressed(evt);
            }
        });
        jPassRepe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassRepeKeyTyped(evt);
            }
        });
        panelCambioContrase.add(jPassRepe, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 220, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CAMBIO CONTRASEÑA");
        panelCambioContrase.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 370, -1));

        labelPresentacion.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        labelPresentacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPresentacion.setText("Ingrese su Usuario");
        panelCambioContrase.add(labelPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 220, -1));

        panelIngresar.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INGRESAR");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelIngresarLayout = new javax.swing.GroupLayout(panelIngresar);
        panelIngresar.setLayout(panelIngresarLayout);
        panelIngresarLayout.setHorizontalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panelIngresarLayout.setVerticalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelCambioContrase.add(panelIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 200, 120, 30));

        labelContraRepe.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        labelContraRepe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContraRepe.setText("Repita la Contraseña");
        panelCambioContrase.add(labelContraRepe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 210, -1));

        labelContra.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        labelContra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContra.setText("Ingrese nueva Contraseña");
        panelCambioContrase.add(labelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 210, -1));

        labelInfo.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        labelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCambioContrase.add(labelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 210, 20));

        panelCambio.setBackground(new java.awt.Color(153, 153, 255));

        labelCambio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelCambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCambio.setText("INGRESAR");
        labelCambio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelCambio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCambio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCambioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCambioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCambioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCambioLayout = new javax.swing.GroupLayout(panelCambio);
        panelCambio.setLayout(panelCambioLayout);
        panelCambioLayout.setHorizontalGroup(
            panelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panelCambioLayout.setVerticalGroup(
            panelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelCambioContrase.add(panelCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 340, 120, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        panelCambioContrase.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 350));

        panelCerrar.setBackground(new java.awt.Color(153, 153, 255));

        labelCerrar.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        labelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCerrar.setText("X");
        labelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCerrarLayout = new javax.swing.GroupLayout(panelCerrar);
        panelCerrar.setLayout(panelCerrarLayout);
        panelCerrarLayout.setHorizontalGroup(
            panelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        panelCerrarLayout.setVerticalGroup(
            panelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCambioContrase.add(panelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCambioContrase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCambioContrase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassKeyTyped
        // TODO add your handling code here:
          int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        jPass.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent evt) {
                if (jPass.getText().length() >= 4) {
                    evt.consume();
                }
            }
        });
    }//GEN-LAST:event_jPassKeyTyped

    private void jPassRepeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassRepeKeyTyped
        // TODO add your handling code here:
          int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        jPassRepe.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent evt) {
                if (jPassRepe.getText().length() >= 4) {
                    evt.consume();
                }
            }
        });
    }//GEN-LAST:event_jPassRepeKeyTyped

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        String usuario = jtUsuario.getText();
        
        boolean confirmacion = false;
        ud = new Usuario_Data();
        Usuario carga = new Usuario();
        
        
        if(ud.buscarUsuario(usuario) == null){
            labelInfo.setText("Usuario no Existe");
        }else{
            String nombre = ud.buscarUsuario(usuario).getNombre();
            nombreUsuario = jtUsuario.getText();
            labelInfo.setText("");
            labelPresentacion.setText("Hola, " + nombre);
            panelIngresar.setVisible(false);
            panelCambio.setVisible(true);
            jPass.setVisible(true);
            jPassRepe.setVisible(true);
            labelContra.setVisible(true);
            labelContraRepe.setVisible(true);
         
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        panelIngresar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        panelIngresar.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_jLabel2MouseExited

    private void labelCambioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCambioMouseClicked
        // TODO add your handling code here:
        String clave = String.valueOf(jPass.getPassword());
        String claveRepe = String.valueOf(jPassRepe.getPassword());
        if(clave.equalsIgnoreCase("****")||clave.isEmpty()||claveRepe.equalsIgnoreCase("****")||claveRepe.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese la Nueva Contraseña");
        }else if(clave.equalsIgnoreCase(claveRepe) ){
                Usuario modificado = new Usuario(nombreUsuario,clave);
                ud.modificarlogin(modificado);
                panelCambioContrase.setVisible(false);
                login.setVisible(true);
        }
            
    }//GEN-LAST:event_labelCambioMouseClicked

    private void labelCambioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCambioMouseEntered
        // TODO add your handling code here:
        panelCambio.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_labelCambioMouseEntered

    private void labelCambioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCambioMouseExited
        // TODO add your handling code here:
        panelCambio.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_labelCambioMouseExited

    private void jPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassMousePressed
        // TODO add your handling code here:
         if (String.valueOf(jPass.getPassword()).equals("****")) {
            jPass.setText("");
            jPass.setForeground(Color.black);
        }
         if (String.valueOf(jPassRepe.getPassword()).isEmpty()) {
            jPassRepe.setText("****");
            jPassRepe.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPassMousePressed

    private void jPassRepeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassRepeMousePressed
        // TODO add your handling code here:
            if (String.valueOf(jPassRepe.getPassword()).equals("****")) {
            jPassRepe.setText("");
            jPassRepe.setForeground(Color.black);
        }
          if (String.valueOf(jPass.getPassword()).isEmpty()) {
            jPass.setText("****");
            jPass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPassRepeMousePressed

    private void jtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuarioMousePressed
        // TODO add your handling code here:
         if (jtUsuario.getText().equals("Ingrese su Usuario")) {
            jtUsuario.setText("");
            jtUsuario.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtUsuarioMousePressed

    private void labelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseClicked
        // TODO add your handling code here:
        panelCambioContrase.setVisible(false);
        login.setVisible(true);
        //menuInstance.setNombrePersona(nombre, apellido);
     
    }//GEN-LAST:event_labelCerrarMouseClicked

    private void labelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseEntered
        // TODO add your handling code here:
        labelCerrar.setFont(labelCerrar.getFont().deriveFont(Font.BOLD));
        labelCerrar.setFont(new java.awt.Font("Arial", 0, 32));
    }//GEN-LAST:event_labelCerrarMouseEntered

    private void labelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseExited
        // TODO add your handling code here:
        labelCerrar.setFont(labelCerrar.getFont().deriveFont(Font.PLAIN));
        labelCerrar.setFont(new java.awt.Font("Arial", 0, 28));
    }//GEN-LAST:event_labelCerrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JPasswordField jPassRepe;
    private javax.swing.JTextField jtUsuario;
    private javax.swing.JLabel labelCambio;
    private javax.swing.JLabel labelCerrar;
    private javax.swing.JLabel labelContra;
    private javax.swing.JLabel labelContraRepe;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelPresentacion;
    private javax.swing.JPanel panelCambio;
    private javax.swing.JPanel panelCambioContrase;
    private javax.swing.JPanel panelCerrar;
    private javax.swing.JPanel panelIngresar;
    // End of variables declaration//GEN-END:variables
}
