/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.transversal.vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import proyecto.transversal.accesoADatos.Alojamiento_Data;
import proyecto.transversal.accesoADatos.Conexion;
import proyecto.transversal.entidades.Ciudad;

/**
 *
 * @author Usuario
 */
public class Prueba_Combobox extends javax.swing.JInternalFrame {
    
    Alojamiento_Data aloja = new Alojamiento_Data();
    Connection con = null;
    /**
     * Creates new form Prueba_Combobox
     */
    public Prueba_Combobox() {
        Conexion.getConexion();
        initComponents();
//        String text = "Argentina";
//        buscarCompleto(text);
        
    }
    
   
    public List<Ciudad> buscarCompleto(String txt){
        
        ArrayList<Ciudad> ciudades = new ArrayList<>();
        
        String sql = "SELECT * FROM ciudad WHERE Nombre LIKE 'Argentina' OR "
                + "Provincia LIKE 'Argentina' OR Pais LIKE 'Argentina' ORDER BY `ciudad`.`Nombre`";
        
//        String sql = "SELECT * FROM ciudad WHERE Nombre LIKE '?%' OR "
//                + "Provincia LIKE '?%' OR Pais LIKE '?%' ORDER BY `ciudad`.`Nombre`";
        
        try{
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, txt);
            ps.setString(2, txt);
            ps.setString(3, txt);
            ResultSet rs = ps.executeQuery();
        if(rs.next()){
            Ciudad ciudad = new Ciudad();
            ciudad.setIdCiudad(rs.getInt("idCiudad"));
            ciudad.setNombreCiudad(rs.getString("Nombre"));
            ciudad.setPais(rs.getString("Pais"));
            ciudad.setProvincia(rs.getString("Provincia"));
            ciudad.setEstado(rs.getBoolean("Estado"));
            ciudades.add(ciudad);
        }
        ps.close();
        
        for(Ciudad lista : ciudades){
            jcbPrueba.addItem(lista);
        }
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al realizar la consulta en ComboBox "+ex);
        }
        return ciudades;
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbPrueba = new javax.swing.JComboBox<>();

        jcbPrueba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jcbPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jcbPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<Object> jcbPrueba;
    // End of variables declaration//GEN-END:variables
}
