/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.transversal.vista;

import com.toedter.calendar.*;
import com.toedter.calendar.demo.DateChooserPanel;
import java.sql.Date;
import java.time.Instant;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;
import proyecto.transversal.accesoADatos.Alojamiento_Data;
import proyecto.transversal.entidades.Alojamiento;

/**
 *
 * @author matia
 */
public class PruebaCalendar extends javax.swing.JPanel {

    /**
     * Creates new form PruebaCalendar
     */
    public PruebaCalendar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbEjecutar = new javax.swing.JButton();
        jdcCalendario = new com.toedter.calendar.JDateChooser();
        jtfIdAlojamiento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jbEjecutar.setText("Ejecutar");
        jbEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEjecutarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Alojamiento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jbEjecutar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jdcCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jtfIdAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jbEjecutar)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(53, 53, 53)
                .addComponent(jdcCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEjecutarActionPerformed
        // TODO add your handling code here:
       
        int id= Integer.parseInt(jtfIdAlojamiento.getText());
        Alojamiento al = new Alojamiento();
        Alojamiento_Data ad = new Alojamiento_Data();
        al = ad.buscarAlojamientoPorId(id);
        LocalDate fecha1= LocalDate.parse("2023-10-15");
        
        LocalDate fecha2= LocalDate.parse("2023-10-19");
        ArrayList <Date> fechasnodisp = new ArrayList<>();
        fechasnodisp.add(Date.valueOf(fecha1));
        fechasnodisp.add(Date.valueOf(fecha2));
        
        for(Date e: fechasnodisp){
        System.out.println("e: "+ e);
        }
        
        jdcCalendario.setMinSelectableDate(Date.valueOf(al.getFechaIn()));
        jdcCalendario.setMaxSelectableDate(Date.valueOf(al.getFechaOn()));
        jdcCalendario.setSelectableDateRange(Date.valueOf(fecha1), Date.valueOf(fecha2));
        
        
        
    }//GEN-LAST:event_jbEjecutarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbEjecutar;
    private com.toedter.calendar.JDateChooser jdcCalendario;
    private javax.swing.JTextField jtfIdAlojamiento;
    // End of variables declaration//GEN-END:variables
}
