/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.transversal.vista;

/**
 *
 * @author matia
 */
public class VistaAlojamiento extends javax.swing.JPanel {

    /**
     * Creates new form VistaAlojamiento
     */
    public VistaAlojamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(600, 700));
        setPreferredSize(new java.awt.Dimension(600, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitulo.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("ALOJAMIENTO");
        add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 260, 20));

        jLabel1.setText("Temporada:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel2.setText("Inicio:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 140, 30));

        jLabel3.setText("Fin:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 50, 20));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 140, 30));

        jLabel4.setText("Nombre de Alojamiento:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel5.setText("Tipo (Hotel, Depto, Casa, etc):");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jTextField1.setText("Concatenar con tipo usando \"-\"");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 310, -1));

        jTextField2.setText("Concatenar y condicionar para txt null");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 230, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 250));

        jLabel6.setText("Descripcion del Servicio:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jCheckBox1.setText("Habilitado");
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        jLabel7.setText("Precio:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jTextField3.setText("Convertir txt a double");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 130, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel11.setText("Nuevo");
        jPanel1.add(jLabel11);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, 80, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel8.setText("Buscar");
        jPanel2.add(jLabel8);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 80, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setText("Guardar");
        jPanel3.add(jLabel9);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 80, 30));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setText("Eliminar");
        jPanel4.add(jLabel10);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 80, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
