/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.transversal.vista;

/**
 *
 * @author matia
 */
public class VistaAlojamiento2 extends javax.swing.JPanel {

    /**
     * Creates new form VistaAlojamiento
     */
    public VistaAlojamiento2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlTitulo = new javax.swing.JLabel();
        jpNuevo = new javax.swing.JPanel();
        jlNuevo = new javax.swing.JLabel();
        jpBuscar = new javax.swing.JPanel();
        jlBuscar = new javax.swing.JLabel();
        jpGuardar = new javax.swing.JPanel();
        jlGuardar = new javax.swing.JLabel();
        jpEliminar = new javax.swing.JPanel();
        jlEliminar = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(600, 700));
        setPreferredSize(new java.awt.Dimension(600, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitulo.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("ALOJAMIENTOS GUARDADOS");
        add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 430, 20));

        jpNuevo.setBackground(new java.awt.Color(244, 231, 187));
        jpNuevo.setMinimumSize(new java.awt.Dimension(0, 0));
        jpNuevo.setPreferredSize(new java.awt.Dimension(100, 30));

        jlNuevo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNuevo.setText("Nuevo");
        jlNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlNuevo.setMaximumSize(new java.awt.Dimension(67, 24));
        jlNuevo.setMinimumSize(new java.awt.Dimension(67, 24));
        jlNuevo.setPreferredSize(new java.awt.Dimension(67, 24));

        javax.swing.GroupLayout jpNuevoLayout = new javax.swing.GroupLayout(jpNuevo);
        jpNuevo.setLayout(jpNuevoLayout);
        jpNuevoLayout.setHorizontalGroup(
            jpNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNuevoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpNuevoLayout.setVerticalGroup(
            jpNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNuevoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, -1, 30));

        jpBuscar.setBackground(new java.awt.Color(244, 231, 187));
        jpBuscar.setMinimumSize(new java.awt.Dimension(0, 0));
        jpBuscar.setPreferredSize(new java.awt.Dimension(100, 30));

        jlBuscar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBuscar.setText("Buscar");
        jlBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlBuscar.setMaximumSize(new java.awt.Dimension(67, 24));
        jlBuscar.setMinimumSize(new java.awt.Dimension(67, 24));
        jlBuscar.setPreferredSize(new java.awt.Dimension(67, 24));

        javax.swing.GroupLayout jpBuscarLayout = new javax.swing.GroupLayout(jpBuscar);
        jpBuscar.setLayout(jpBuscarLayout);
        jpBuscarLayout.setHorizontalGroup(
            jpBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpBuscarLayout.setVerticalGroup(
            jpBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        jpGuardar.setBackground(new java.awt.Color(244, 231, 187));
        jpGuardar.setMinimumSize(new java.awt.Dimension(0, 0));
        jpGuardar.setPreferredSize(new java.awt.Dimension(100, 30));

        jlGuardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlGuardar.setText("Guardar");
        jlGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGuardar.setMaximumSize(new java.awt.Dimension(67, 24));
        jlGuardar.setMinimumSize(new java.awt.Dimension(67, 24));
        jlGuardar.setPreferredSize(new java.awt.Dimension(67, 24));

        javax.swing.GroupLayout jpGuardarLayout = new javax.swing.GroupLayout(jpGuardar);
        jpGuardar.setLayout(jpGuardarLayout);
        jpGuardarLayout.setHorizontalGroup(
            jpGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpGuardarLayout.setVerticalGroup(
            jpGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, -1, 30));

        jpEliminar.setBackground(new java.awt.Color(244, 231, 187));
        jpEliminar.setMinimumSize(new java.awt.Dimension(0, 0));
        jpEliminar.setPreferredSize(new java.awt.Dimension(100, 30));

        jlEliminar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEliminar.setText("Eliminar");
        jlEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlEliminar.setMaximumSize(new java.awt.Dimension(67, 24));
        jlEliminar.setMinimumSize(new java.awt.Dimension(67, 24));
        jlEliminar.setPreferredSize(new java.awt.Dimension(67, 24));

        javax.swing.GroupLayout jpEliminarLayout = new javax.swing.GroupLayout(jpEliminar);
        jpEliminar.setLayout(jpEliminarLayout);
        jpEliminarLayout.setHorizontalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpEliminarLayout.setVerticalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 640, -1, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 480, 240));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 130, 30));

        jLabel1.setText("Por fecha:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 80, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jlBuscar;
    private javax.swing.JLabel jlEliminar;
    private javax.swing.JLabel jlGuardar;
    private javax.swing.JLabel jlNuevo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPanel jpBuscar;
    private javax.swing.JPanel jpEliminar;
    private javax.swing.JPanel jpGuardar;
    private javax.swing.JPanel jpNuevo;
    // End of variables declaration//GEN-END:variables
}
