/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.transversal.vista;

/**
 *
 * @author matia
 */
public class VistaAlojamiento extends javax.swing.JPanel {

    /**
     * Creates new form VistaAlojamiento
     */
    public VistaAlojamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlTemporada = new javax.swing.JLabel();
        jlInicio = new javax.swing.JLabel();
        jdcInicio = new com.toedter.calendar.JDateChooser();
        jlFin = new javax.swing.JLabel();
        jdcFin = new com.toedter.calendar.JDateChooser();
        jlNombreAlojamiento = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jtfNombreAlojamiento = new javax.swing.JTextField();
        jtfTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescServicio = new javax.swing.JTextArea();
        jlDescServicio = new javax.swing.JLabel();
        jcbHabilitado = new javax.swing.JCheckBox();
        jlPrecio = new javax.swing.JLabel();
        jtfPrecio = new javax.swing.JTextField();
        jpNuevo = new javax.swing.JPanel();
        jlNuevo = new javax.swing.JLabel();
        jpBuscar = new javax.swing.JPanel();
        jlBuscar = new javax.swing.JLabel();
        jpGuardar = new javax.swing.JPanel();
        jlGuardar = new javax.swing.JLabel();
        jpEliminar = new javax.swing.JPanel();
        jlEliminar = new javax.swing.JLabel();
        jlEtc = new javax.swing.JLabel();
        jsCantHabitaciones = new javax.swing.JSpinner();
        jlHabitaciones = new javax.swing.JLabel();
        jlCantidadDe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(600, 700));
        setPreferredSize(new java.awt.Dimension(600, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitulo.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("ALOJAMIENTO");
        add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 260, 20));

        jlTemporada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlTemporada.setText("Temporada:");
        add(jlTemporada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jlInicio.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jlInicio.setText("Inicio:");
        add(jlInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jdcInicio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add(jdcInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 150, 30));

        jlFin.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jlFin.setText("Fin:");
        add(jlFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 30, 20));

        jdcFin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add(jdcFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 150, 30));

        jlNombreAlojamiento.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jlNombreAlojamiento.setText("Nombre de Alojamiento:");
        add(jlNombreAlojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jlTipo.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jlTipo.setText("Tipo:");
        add(jlTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 40, -1));

        jtfNombreAlojamiento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfNombreAlojamiento.setText("Concatenar con tipo usando \"-\"");
        add(jtfNombreAlojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 320, 30));

        jtfTipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfTipo.setText("Concatenar y condicionar para txt null");
        add(jtfTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 320, 30));

        jtaDescServicio.setColumns(20);
        jtaDescServicio.setRows(5);
        jScrollPane1.setViewportView(jtaDescServicio);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 260, 250));

        jlDescServicio.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jlDescServicio.setText("Descripcion del Servicio:");
        add(jlDescServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jcbHabilitado.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jcbHabilitado.setText("Habilitado");
        add(jcbHabilitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 110, 30));

        jlPrecio.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jlPrecio.setText("Precio:");
        add(jlPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        jtfPrecio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfPrecio.setText("Convertir txt a double");
        add(jtfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 170, 30));

        jpNuevo.setBackground(new java.awt.Color(244, 231, 187));
        jpNuevo.setMinimumSize(new java.awt.Dimension(0, 0));
        jpNuevo.setPreferredSize(new java.awt.Dimension(100, 30));

        jlNuevo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNuevo.setText("Nuevo");
        jlNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlNuevo.setMaximumSize(new java.awt.Dimension(67, 24));
        jlNuevo.setMinimumSize(new java.awt.Dimension(67, 24));
        jlNuevo.setPreferredSize(new java.awt.Dimension(67, 24));

        javax.swing.GroupLayout jpNuevoLayout = new javax.swing.GroupLayout(jpNuevo);
        jpNuevo.setLayout(jpNuevoLayout);
        jpNuevoLayout.setHorizontalGroup(
            jpNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNuevoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpNuevoLayout.setVerticalGroup(
            jpNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNuevoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 660, -1, 30));

        jpBuscar.setBackground(new java.awt.Color(244, 231, 187));
        jpBuscar.setMinimumSize(new java.awt.Dimension(0, 0));
        jpBuscar.setPreferredSize(new java.awt.Dimension(100, 30));

        jlBuscar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBuscar.setText("Buscar");
        jlBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlBuscar.setMaximumSize(new java.awt.Dimension(67, 24));
        jlBuscar.setMinimumSize(new java.awt.Dimension(67, 24));
        jlBuscar.setPreferredSize(new java.awt.Dimension(67, 24));

        javax.swing.GroupLayout jpBuscarLayout = new javax.swing.GroupLayout(jpBuscar);
        jpBuscar.setLayout(jpBuscarLayout);
        jpBuscarLayout.setHorizontalGroup(
            jpBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpBuscarLayout.setVerticalGroup(
            jpBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, -1, 30));

        jpGuardar.setBackground(new java.awt.Color(244, 231, 187));
        jpGuardar.setMinimumSize(new java.awt.Dimension(0, 0));
        jpGuardar.setPreferredSize(new java.awt.Dimension(100, 30));

        jlGuardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlGuardar.setText("Guardar");
        jlGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGuardar.setMaximumSize(new java.awt.Dimension(67, 24));
        jlGuardar.setMinimumSize(new java.awt.Dimension(67, 24));
        jlGuardar.setPreferredSize(new java.awt.Dimension(67, 24));

        javax.swing.GroupLayout jpGuardarLayout = new javax.swing.GroupLayout(jpGuardar);
        jpGuardar.setLayout(jpGuardarLayout);
        jpGuardarLayout.setHorizontalGroup(
            jpGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpGuardarLayout.setVerticalGroup(
            jpGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, -1, 30));

        jpEliminar.setBackground(new java.awt.Color(244, 231, 187));
        jpEliminar.setMinimumSize(new java.awt.Dimension(0, 0));
        jpEliminar.setPreferredSize(new java.awt.Dimension(100, 30));

        jlEliminar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEliminar.setText("Eliminar");
        jlEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlEliminar.setMaximumSize(new java.awt.Dimension(67, 24));
        jlEliminar.setMinimumSize(new java.awt.Dimension(67, 24));
        jlEliminar.setPreferredSize(new java.awt.Dimension(67, 24));

        javax.swing.GroupLayout jpEliminarLayout = new javax.swing.GroupLayout(jpEliminar);
        jpEliminar.setLayout(jpEliminarLayout);
        jpEliminarLayout.setHorizontalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpEliminarLayout.setVerticalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 660, -1, 30));

        jlEtc.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jlEtc.setText("(Hotel, Dpto, Casa, etc.)");
        add(jlEtc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));
        add(jsCantHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 70, 30));

        jlHabitaciones.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jlHabitaciones.setText("Habitaciones:");
        add(jlHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        jlCantidadDe.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jlCantidadDe.setText("Cantidad de");
        add(jlCantidadDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbHabilitado;
    private com.toedter.calendar.JDateChooser jdcFin;
    private com.toedter.calendar.JDateChooser jdcInicio;
    private javax.swing.JLabel jlBuscar;
    private javax.swing.JLabel jlCantidadDe;
    private javax.swing.JLabel jlDescServicio;
    private javax.swing.JLabel jlEliminar;
    private javax.swing.JLabel jlEtc;
    private javax.swing.JLabel jlFin;
    private javax.swing.JLabel jlGuardar;
    private javax.swing.JLabel jlHabitaciones;
    private javax.swing.JLabel jlInicio;
    private javax.swing.JLabel jlNombreAlojamiento;
    private javax.swing.JLabel jlNuevo;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JLabel jlTemporada;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPanel jpBuscar;
    private javax.swing.JPanel jpEliminar;
    private javax.swing.JPanel jpGuardar;
    private javax.swing.JPanel jpNuevo;
    private javax.swing.JSpinner jsCantHabitaciones;
    private javax.swing.JTextArea jtaDescServicio;
    private javax.swing.JTextField jtfNombreAlojamiento;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfTipo;
    // End of variables declaration//GEN-END:variables
}
