/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.transversal.vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import proyecto.transversal.accesoADatos.Ciudad_Data;
import proyecto.transversal.entidades.Ciudad;

/**
 *
 * @author ferben007
 */
public class VistaCiudad extends javax.swing.JPanel {

    private Ciudad_Data cd = new Ciudad_Data();
    private DefaultListModel modeloHabi = new DefaultListModel();
    private DefaultListModel modeloDesah = new DefaultListModel();
    private int id;

    /**
     * Creates new form VistaCiudad
     */
    public VistaCiudad() {

        initComponents();
        //cargarCiudades();
        desabilitaButton();
        desabilitarTexField();
        jScrollPane3.setVisible(false);
        cerrarBusqueda();
        panelCerrar.setVisible(false);
        //cargarCiudadesDeshabilitadas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ImageIcon icono= new ImageIcon(getClass().getResource("/imagenes/fondo2.png"));
        Image imagen=icono.getImage();
        panelPrincipal = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            }

        };
        jScrollPane1 = new javax.swing.JScrollPane();
        listCiudades = new javax.swing.JList<>();
        labelTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtexProvincia = new javax.swing.JTextField();
        jtexCiudad = new javax.swing.JTextField();
        jtexPais = new javax.swing.JTextField();
        panelEliminar = new javax.swing.JPanel();
        labelEliminar = new javax.swing.JLabel();
        panelGuardar = new javax.swing.JPanel();
        labelGuardar = new javax.swing.JLabel();
        panelModificar = new javax.swing.JPanel();
        labelModificar = new javax.swing.JLabel();
        panelNuevo = new javax.swing.JPanel();
        labelNuevo = new javax.swing.JLabel();
        panelBusProvincia = new javax.swing.JPanel();
        labelBusProvincia = new javax.swing.JLabel();
        panelBusPais = new javax.swing.JPanel();
        labelBusPais = new javax.swing.JLabel();
        jtexBusProvincia = new javax.swing.JTextField();
        jtexBusPais = new javax.swing.JTextField();
        panelXPais = new javax.swing.JPanel();
        labelXPais = new javax.swing.JLabel();
        panelXProvincia = new javax.swing.JPanel();
        labelXProvincia = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelMosCiudadesHabilitadas = new javax.swing.JPanel();
        labelMosCiudadesHabilitadas = new javax.swing.JLabel();
        panelMosCiudadesDeshabilitadas = new javax.swing.JPanel();
        labelMosCiudadesDeshabilitadas = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDeshabilitadas = new javax.swing.JList<>();
        labeCiudad = new javax.swing.JLabel();
        panelCerrar = new javax.swing.JPanel();
        labelCerrar = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        labelSalir = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        panelPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listCiudades.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        listCiudades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCiudadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listCiudades);

        panelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 280, 180));

        labelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("CIUDAD");
        panelPrincipal.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 43, 517, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de Pais");
        panelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 115, 150, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre de Ciudad");
        panelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre de Provincia");
        panelPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jtexProvincia.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jtexProvincia.setForeground(java.awt.Color.gray);
        jtexProvincia.setText("Ingrese una Provincia");
        jtexProvincia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtexProvinciaMousePressed(evt);
            }
        });
        jtexProvincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtexProvinciaKeyTyped(evt);
            }
        });
        panelPrincipal.add(jtexProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 250, -1));

        jtexCiudad.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jtexCiudad.setForeground(java.awt.Color.gray);
        jtexCiudad.setText("Ingrese una Ciudad");
        jtexCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtexCiudadMousePressed(evt);
            }
        });
        jtexCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtexCiudadActionPerformed(evt);
            }
        });
        jtexCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtexCiudadKeyTyped(evt);
            }
        });
        panelPrincipal.add(jtexCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 250, -1));

        jtexPais.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jtexPais.setForeground(java.awt.Color.gray);
        jtexPais.setText("Ingrese un Pais");
        jtexPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtexPaisMousePressed(evt);
            }
        });
        jtexPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtexPaisKeyTyped(evt);
            }
        });
        panelPrincipal.add(jtexPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 250, -1));

        panelEliminar.setBackground(new java.awt.Color(0, 0, 102));

        labelEliminar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelEliminar.setForeground(new java.awt.Color(255, 255, 255));
        labelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEliminar.setText("ELIMINAR");
        labelEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 110, 30));

        panelGuardar.setBackground(new java.awt.Color(0, 0, 102));

        labelGuardar.setBackground(new java.awt.Color(0, 0, 102));
        labelGuardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelGuardar.setForeground(new java.awt.Color(255, 255, 255));
        labelGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGuardar.setText("GUARDAR");
        labelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 110, 30));

        panelModificar.setBackground(new java.awt.Color(0, 0, 102));

        labelModificar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModificar.setText("MODIFICAR");
        labelModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelModificarLayout = new javax.swing.GroupLayout(panelModificar);
        panelModificar.setLayout(panelModificarLayout);
        panelModificarLayout.setHorizontalGroup(
            panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelModificarLayout.setVerticalGroup(
            panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 110, 30));

        panelNuevo.setBackground(new java.awt.Color(0, 0, 102));

        labelNuevo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelNuevo.setForeground(new java.awt.Color(255, 255, 255));
        labelNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNuevo.setText("NUEVO");
        labelNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelNuevoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelNuevoLayout = new javax.swing.GroupLayout(panelNuevo);
        panelNuevo.setLayout(panelNuevoLayout);
        panelNuevoLayout.setHorizontalGroup(
            panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelNuevoLayout.setVerticalGroup(
            panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 30));

        panelBusProvincia.setBackground(new java.awt.Color(0, 0, 102));

        labelBusProvincia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelBusProvincia.setForeground(new java.awt.Color(255, 255, 255));
        labelBusProvincia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBusProvincia.setText("Busqueda por Provincia");
        labelBusProvincia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelBusProvincia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBusProvincia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBusProvinciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBusProvinciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBusProvinciaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBusProvinciaLayout = new javax.swing.GroupLayout(panelBusProvincia);
        panelBusProvincia.setLayout(panelBusProvinciaLayout);
        panelBusProvinciaLayout.setHorizontalGroup(
            panelBusProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBusProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBusProvinciaLayout.setVerticalGroup(
            panelBusProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBusProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBusProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 185, 30));

        panelBusPais.setBackground(new java.awt.Color(0, 0, 102));

        labelBusPais.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelBusPais.setForeground(new java.awt.Color(255, 255, 255));
        labelBusPais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBusPais.setText("Busqueda por Pais");
        labelBusPais.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelBusPais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBusPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBusPaisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBusPaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBusPaisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBusPaisLayout = new javax.swing.GroupLayout(panelBusPais);
        panelBusPais.setLayout(panelBusPaisLayout);
        panelBusPaisLayout.setHorizontalGroup(
            panelBusPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBusPais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBusPaisLayout.setVerticalGroup(
            panelBusPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBusPais, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelBusPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 185, 30));

        jtexBusProvincia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtexBusProvinciaFocusGained(evt);
            }
        });
        jtexBusProvincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtexBusProvinciaKeyReleased(evt);
            }
        });
        panelPrincipal.add(jtexBusProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 185, 30));

        jtexBusPais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtexBusPaisFocusGained(evt);
            }
        });
        jtexBusPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtexBusPaisKeyReleased(evt);
            }
        });
        panelPrincipal.add(jtexBusPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 185, 30));

        labelXPais.setFont(new java.awt.Font("Segoe Script", 0, 22)); // NOI18N
        labelXPais.setForeground(new java.awt.Color(255, 51, 51));
        labelXPais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelXPais.setText("X");
        labelXPais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelXPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelXPaisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelXPaisLayout = new javax.swing.GroupLayout(panelXPais);
        panelXPais.setLayout(panelXPaisLayout);
        panelXPaisLayout.setHorizontalGroup(
            panelXPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelXPais, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        panelXPaisLayout.setVerticalGroup(
            panelXPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelXPais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelXPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 30, 30));

        labelXProvincia.setFont(new java.awt.Font("Segoe Script", 0, 22)); // NOI18N
        labelXProvincia.setForeground(new java.awt.Color(255, 51, 51));
        labelXProvincia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelXProvincia.setText("X");
        labelXProvincia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelXProvincia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelXProvinciaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelXProvinciaLayout = new javax.swing.GroupLayout(panelXProvincia);
        panelXProvincia.setLayout(panelXProvinciaLayout);
        panelXProvinciaLayout.setHorizontalGroup(
            panelXProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelXProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        panelXProvinciaLayout.setVerticalGroup(
            panelXProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelXProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelXProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, 30, 30));
        panelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 580, 10));

        panelMosCiudadesHabilitadas.setBackground(new java.awt.Color(0, 0, 102));

        labelMosCiudadesHabilitadas.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        labelMosCiudadesHabilitadas.setForeground(new java.awt.Color(255, 255, 255));
        labelMosCiudadesHabilitadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMosCiudadesHabilitadas.setText("MOSTRAR CIUDADES HABILITADAS");
        labelMosCiudadesHabilitadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelMosCiudadesHabilitadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMosCiudadesHabilitadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMosCiudadesHabilitadasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMosCiudadesHabilitadasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMosCiudadesHabilitadasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMosCiudadesHabilitadasLayout = new javax.swing.GroupLayout(panelMosCiudadesHabilitadas);
        panelMosCiudadesHabilitadas.setLayout(panelMosCiudadesHabilitadasLayout);
        panelMosCiudadesHabilitadasLayout.setHorizontalGroup(
            panelMosCiudadesHabilitadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMosCiudadesHabilitadas, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        panelMosCiudadesHabilitadasLayout.setVerticalGroup(
            panelMosCiudadesHabilitadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMosCiudadesHabilitadas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelMosCiudadesHabilitadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 300, 30));

        panelMosCiudadesDeshabilitadas.setBackground(new java.awt.Color(244, 231, 187));

        labelMosCiudadesDeshabilitadas.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        labelMosCiudadesDeshabilitadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMosCiudadesDeshabilitadas.setText("MOSTRAR CIUDADES DESHABILITADAS");
        labelMosCiudadesDeshabilitadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelMosCiudadesDeshabilitadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMosCiudadesDeshabilitadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMosCiudadesDeshabilitadasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMosCiudadesDeshabilitadasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMosCiudadesDeshabilitadasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMosCiudadesDeshabilitadasLayout = new javax.swing.GroupLayout(panelMosCiudadesDeshabilitadas);
        panelMosCiudadesDeshabilitadas.setLayout(panelMosCiudadesDeshabilitadasLayout);
        panelMosCiudadesDeshabilitadasLayout.setHorizontalGroup(
            panelMosCiudadesDeshabilitadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMosCiudadesDeshabilitadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMosCiudadesDeshabilitadasLayout.setVerticalGroup(
            panelMosCiudadesDeshabilitadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMosCiudadesDeshabilitadas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelMosCiudadesDeshabilitadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 300, 30));

        labelInfo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelInfo.setForeground(new java.awt.Color(0, 0, 0));
        labelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelPrincipal.add(labelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 280, 20));

        listaDeshabilitadas.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        listaDeshabilitadas.setForeground(new java.awt.Color(255, 0, 51));
        listaDeshabilitadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDeshabilitadasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaDeshabilitadas);

        panelPrincipal.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 540, 200));

        labeCiudad.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        labeCiudad.setForeground(new java.awt.Color(0, 0, 0));
        panelPrincipal.add(labeCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 300, 20));

        panelCerrar.setBackground(new java.awt.Color(0, 0, 102));

        labelCerrar.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        labelCerrar.setForeground(new java.awt.Color(255, 255, 255));
        labelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCerrar.setText("CERRAR MUESTRAS");
        labelCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCerrarLayout = new javax.swing.GroupLayout(panelCerrar);
        panelCerrar.setLayout(panelCerrarLayout);
        panelCerrarLayout.setHorizontalGroup(
            panelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        panelCerrarLayout.setVerticalGroup(
            panelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 170, 30));

        panelSalir.setBackground(new java.awt.Color(0, 0, 102));

        labelSalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelSalir.setForeground(new java.awt.Color(255, 255, 255));
        labelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSalir.setText("SALIR");
        labelSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtexCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtexCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtexCiudadActionPerformed

    private void jtexPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtexPaisKeyTyped
        int key = evt.getKeyChar();
        boolean letrasMin = key >= 97 && key <= 122;
        boolean letrasMay = key >= 65 && key <= 90;
        boolean espacio = key == 32;
        if (!(letrasMin || letrasMay || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtexPaisKeyTyped

    private void jtexProvinciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtexProvinciaKeyTyped
        int key = evt.getKeyChar();
        boolean letrasMin = key >= 97 && key <= 122;
        boolean letrasMay = key >= 65 && key <= 90;
        boolean espacio = key == 32;
        if (!(letrasMin || letrasMay || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtexProvinciaKeyTyped

    private void jtexCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtexCiudadKeyTyped
        int key = evt.getKeyChar();
        boolean letrasMin = key >= 97 && key <= 122;
        boolean letrasMay = key >= 65 && key <= 90;
        boolean espacio = key == 32;
        if (!(letrasMin || letrasMay || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtexCiudadKeyTyped

    private void labelNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNuevoMouseEntered
        // TODO add your handling code here:
        panelNuevo.setBackground(new Color(103, 71, 48));
        labelNuevo.setForeground(Color.white);
    }//GEN-LAST:event_labelNuevoMouseEntered

    private void labelNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNuevoMouseExited
        // TODO add your handling code here:
        panelNuevo.setBackground(new Color(244, 231, 187));
        labelNuevo.setForeground(Color.black);
    }//GEN-LAST:event_labelNuevoMouseExited

    private void jtexPaisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtexPaisMousePressed
        // TODO add your handling code here:
        limpiarPais();
    }//GEN-LAST:event_jtexPaisMousePressed

    private void jtexProvinciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtexProvinciaMousePressed
        // TODO add your handling code here:
        limpiarProvincia();
    }//GEN-LAST:event_jtexProvinciaMousePressed

    private void jtexCiudadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtexCiudadMousePressed
        // TODO add your handling code here:
        limpiarCiudad();
    }//GEN-LAST:event_jtexCiudadMousePressed

    private void labelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuardarMouseEntered
        // TODO add your handling code here:
        panelGuardar.setBackground(new Color(103, 71, 48));
        labelGuardar.setForeground(Color.white);
    }//GEN-LAST:event_labelGuardarMouseEntered

    private void labelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuardarMouseExited
        // TODO add your handling code here:
        panelGuardar.setBackground(new Color(244, 231, 187));
        labelGuardar.setForeground(Color.black);
    }//GEN-LAST:event_labelGuardarMouseExited

    private void labelEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarMouseEntered
        // TODO add your handling code here:
        panelEliminar.setBackground(new Color(103, 71, 48));
        labelEliminar.setForeground(Color.white);
    }//GEN-LAST:event_labelEliminarMouseEntered

    private void labelEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarMouseExited
        // TODO add your handling code here:
        panelEliminar.setBackground(new Color(244, 231, 187));
        labelEliminar.setForeground(Color.black);
    }//GEN-LAST:event_labelEliminarMouseExited

    private void labelModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarMouseEntered
        // TODO add your handling code here:
        panelModificar.setBackground(new Color(103, 71, 48));
        labelModificar.setForeground(Color.white);
    }//GEN-LAST:event_labelModificarMouseEntered

    private void labelModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarMouseExited
        // TODO add your handling code here:
        panelModificar.setBackground(new Color(244, 231, 187));
        labelModificar.setForeground(Color.black);
    }//GEN-LAST:event_labelModificarMouseExited

    private void labelNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNuevoMouseClicked
        // TODO add your handling code here:
        limpiarTodo();
    }//GEN-LAST:event_labelNuevoMouseClicked

    private void labelBusPaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBusPaisMouseExited
        // TODO add your handling code here:
        panelBusPais.setBackground(new Color(244, 231, 187));
        labelBusPais.setForeground(Color.black);
    }//GEN-LAST:event_labelBusPaisMouseExited

    private void labelBusPaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBusPaisMouseEntered
        // TODO add your handling code here:
        panelBusPais.setBackground(new Color(103, 71, 48));
        labelBusPais.setForeground(Color.white);
    }//GEN-LAST:event_labelBusPaisMouseEntered

    private void labelBusProvinciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBusProvinciaMouseEntered
        // TODO add your handling code here:
        panelBusProvincia.setBackground(new Color(103, 71, 48));
        labelBusProvincia.setForeground(Color.white);
    }//GEN-LAST:event_labelBusProvinciaMouseEntered

    private void labelBusProvinciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBusProvinciaMouseExited
        // TODO add your handling code here:
        panelBusProvincia.setBackground(new Color(244, 231, 187));
        labelBusProvincia.setForeground(Color.black);
    }//GEN-LAST:event_labelBusProvinciaMouseExited

    private void labelXPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelXPaisMouseClicked
        // TODO add your handling code here:
        jtexBusPais.setVisible(false);
        jtexBusPais.setText("");
        panelXPais.setVisible(false);
        labelXPais.setVisible(false);
        modeloHabi.removeAllElements();
        cargarCiudades();
    }//GEN-LAST:event_labelXPaisMouseClicked

    private void labelXProvinciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelXProvinciaMouseClicked
        // TODO add your handling code here:
        jtexBusProvincia.setVisible(false);
        jtexBusProvincia.setText("");
        panelXProvincia.setVisible(false);
        labelXProvincia.setVisible(false);
        modeloHabi.removeAllElements();
        cargarCiudades();

    }//GEN-LAST:event_labelXProvinciaMouseClicked

    private void labelBusPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBusPaisMouseClicked
        // TODO add your handling code here:
        jtexBusPais.setVisible(true);
        panelXPais.setVisible(true);
        labelXPais.setVisible(true);
        jtexBusProvincia.setVisible(false);
        panelXProvincia.setVisible(false);
        labelXProvincia.setVisible(false);
        jtexBusProvincia.setText("");
        modeloHabi.removeAllElements();
        //cargarCiudades();
        limpiarTodo();

    }//GEN-LAST:event_labelBusPaisMouseClicked

    private void labelBusProvinciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBusProvinciaMouseClicked
        // TODO add your handling code here:
        jtexBusProvincia.setVisible(true);
        panelXProvincia.setVisible(true);
        labelXProvincia.setVisible(true);
        jtexBusPais.setVisible(false);
        panelXPais.setVisible(false);
        labelXPais.setVisible(false);
        jtexBusPais.setText("");
        modeloHabi.removeAllElements();
        //cargarCiudades();
        limpiarTodo();
    }//GEN-LAST:event_labelBusProvinciaMouseClicked

    private void labelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuardarMouseClicked
        // TODO add your handling code here:
        if (jtexPais.getText().equalsIgnoreCase("Ingrese un Pais") || jtexProvincia.getText().equalsIgnoreCase("Ingrese una Provincia") || jtexCiudad.getText().equalsIgnoreCase("Ingrese una Ciudad")
                || jtexPais.getText().isEmpty() || jtexProvincia.getText().isEmpty() || jtexCiudad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los Campos deben estar LLenos!!!");
        } else {
            String pais = jtexPais.getText();
            pais = convierteMayuscula(pais);
            String provincia = jtexProvincia.getText();
            provincia = convierteMayuscula(provincia);
            String ciudad = jtexCiudad.getText();
            ciudad = convierteMayuscula(ciudad);
            boolean repetido = false;
            for (Ciudad bus : cd.obtenerCiudad()) {
                if (ciudad.equalsIgnoreCase(bus.getNombreCiudad())) {
                    repetido = true;
                    JOptionPane.showMessageDialog(null, "La Ciudad ya EXISTE!!!");
                }
            }
            System.out.println(repetido);
            if (repetido == false) {
                Ciudad carga = new Ciudad(pais, ciudad, provincia, true);
                cd.agregarCiudad(carga);
                modeloHabi.removeAllElements();
                cargarCiudades();
                limpiarTodo();
            }
        }
    }//GEN-LAST:event_labelGuardarMouseClicked

    private void listCiudadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCiudadesMouseClicked

        if (evt.getClickCount() == 2) { // Doble clic
            int idCiudad = listCiudades.getSelectedValue().getIdCiudad();
            Ciudad carga = cd.buscarCiudadPorID(idCiudad);
            jtexPais.setForeground(Color.black);
            jtexProvincia.setForeground(Color.black);
            jtexCiudad.setForeground(Color.black);
            jtexPais.setText(carga.getPais());
            jtexProvincia.setText(carga.getProvincia());
            jtexCiudad.setText(carga.getNombreCiudad());
            id = carga.getIdCiudad();
            panelGuardar.setVisible(false);
            panelModificar.setVisible(true);
            labelModificar.setVisible(true);
            panelEliminar.setVisible(true);
            labelEliminar.setVisible(true);
            desabilitarTexField();
            
        }
    }//GEN-LAST:event_listCiudadesMouseClicked

    private void labelMosCiudadesHabilitadasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMosCiudadesHabilitadasMouseEntered
        // TODO add your handling code here:
        panelMosCiudadesHabilitadas.setBackground(new Color(103, 71, 48));
        labelMosCiudadesHabilitadas.setForeground(Color.white);
    }//GEN-LAST:event_labelMosCiudadesHabilitadasMouseEntered

    private void labelMosCiudadesHabilitadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMosCiudadesHabilitadasMouseExited
        // TODO add your handling code here:
        panelMosCiudadesHabilitadas.setBackground(new Color(244, 231, 187));
        labelMosCiudadesHabilitadas.setForeground(Color.black);
    }//GEN-LAST:event_labelMosCiudadesHabilitadasMouseExited

    private void labelMosCiudadesHabilitadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMosCiudadesHabilitadasMouseClicked
        // TODO add your handling code here:
        modeloHabi.removeAllElements();
        cargarCiudades();
        labeCiudad.setText("CIUDADES HABILITADAS");
        labelInfo.setText("Hacer doble click para cargarlas.");
        jScrollPane1.setVisible(true);
        panelBusPais.setVisible(true);
        panelBusProvincia.setVisible(true);
        jScrollPane3.setVisible(false);
        panelMosCiudadesHabilitadas.setVisible(false);
        panelMosCiudadesDeshabilitadas.setVisible(true);
        limpiarTodo();
        panelCerrar.setVisible(true);

    }//GEN-LAST:event_labelMosCiudadesHabilitadasMouseClicked

    private void labelMosCiudadesDeshabilitadasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMosCiudadesDeshabilitadasMouseEntered
        // TODO add your handling code here:
        panelMosCiudadesDeshabilitadas.setBackground(new Color(103, 71, 48));
        labelMosCiudadesDeshabilitadas.setForeground(Color.white);
    }//GEN-LAST:event_labelMosCiudadesDeshabilitadasMouseEntered

    private void labelMosCiudadesDeshabilitadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMosCiudadesDeshabilitadasMouseExited
        // TODO add your handling code here:
        panelMosCiudadesDeshabilitadas.setBackground(new Color(244, 231, 187));
        labelMosCiudadesDeshabilitadas.setForeground(Color.black);
    }//GEN-LAST:event_labelMosCiudadesDeshabilitadasMouseExited

    private void labelMosCiudadesDeshabilitadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMosCiudadesDeshabilitadasMouseClicked
        // TODO add your handling code here:
        modeloDesah.removeAllElements();
        cargarCiudadesDeshabilitadas();
        labeCiudad.setText("CIUDADES ELIMINADAS");
        labelInfo.setText("Hacer doble click para añadirlas.");
        jScrollPane3.setVisible(true);
        cerrarBusqueda();
        limpiarTodo();
    }//GEN-LAST:event_labelMosCiudadesDeshabilitadasMouseClicked

    private void listaDeshabilitadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeshabilitadasMouseClicked
        // TODO add your handling code here:
        try{
        if (evt.getClickCount() == 2) { // Doble clic
            int idCiudad = listaDeshabilitadas.getSelectedValue().getIdCiudad();
            int op = JOptionPane.showConfirmDialog(null, "Esta seguro de AGREGAR la ciudad", "Gracias", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                cd.rehabilitarCiudad(idCiudad);
                refrescarTablas();
            }
        }
        }catch(NullPointerException a){
        }
        

    }//GEN-LAST:event_listaDeshabilitadasMouseClicked

    private void labelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarMouseClicked
        // Elimina la ciudad

                int op = JOptionPane.showConfirmDialog(null, "Esta seguro que decea ELIMINAR la ciudad", "Gracias", JOptionPane.YES_NO_OPTION);
                if (op == 0) {
                    cd.eliminarCiudad(id);
                    refrescarTablas();
                    limpiarTodo();
                    panelGuardar.setVisible(true);
                    labelGuardar.setVisible(true);
                    panelEliminar.setVisible(false);
                    labelEliminar.setVisible(false);
                    panelModificar.setVisible(false);
                    labelModificar.setVisible(false);
                }
    }//GEN-LAST:event_labelEliminarMouseClicked

    private void jtexBusPaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtexBusPaisKeyReleased
        //Busca una ciudad al ingresa la primera letra
        if (jtexBusPais.getText().isEmpty()) {
            modeloHabi.removeAllElements();
        } else {
            modeloHabi.removeAllElements();
            for (Ciudad bus : cd.obtenerCiudadHabilitada()) {
                if (bus.getPais().toUpperCase().startsWith(jtexBusPais.getText().toUpperCase())) {
                    modeloHabi.addElement(bus);
                }
            }
        }

    }//GEN-LAST:event_jtexBusPaisKeyReleased

    private void jtexBusProvinciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtexBusProvinciaKeyReleased
        // Busca una Provincia la ingresar la primera letra
         if (jtexBusProvincia.getText().isEmpty()) {
            modeloHabi.removeAllElements();
        } else {
            modeloHabi.removeAllElements();
            for (Ciudad bus : cd.obtenerCiudadHabilitada()) {
                if (bus.getProvincia().toUpperCase().startsWith(jtexBusProvincia.getText().toUpperCase())) {
                    modeloHabi.addElement(bus);
                }
            }
        }
    }//GEN-LAST:event_jtexBusProvinciaKeyReleased

    private void jtexBusPaisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtexBusPaisFocusGained
        // Cuando hace foco limpia la lista
        modeloHabi.removeAllElements();
    }//GEN-LAST:event_jtexBusPaisFocusGained

    private void labelModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarMouseClicked
        // modifica la ciudad
        
        String pais = jtexPais.getText().trim();
        String provincia = jtexProvincia.getText().trim();
        String ciudad = jtexCiudad.getText().trim();
        Ciudad carga = new Ciudad(id, pais, ciudad, provincia, true);
        cd.modificarCiudad(carga);
        modeloHabi.removeAllElements();
        cargarCiudades();//metodo que carga la lista de ciudad
        limpiarTodo();//limpia los capos de creacion de la ciudad
        
            
       
    }//GEN-LAST:event_labelModificarMouseClicked

    private void jtexBusProvinciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtexBusProvinciaFocusGained
        // Cuando hace foco limpia la lista:
        modeloHabi.removeAllElements();
    }//GEN-LAST:event_jtexBusProvinciaFocusGained

    private void labelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseExited
        // TODO add your handling code here:
        panelCerrar.setBackground(new Color(244,231,187));
        labelCerrar.setForeground(Color.black);
    }//GEN-LAST:event_labelCerrarMouseExited

    private void labelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseClicked
        // TODO add your handling code here:
        jScrollPane1.setVisible(false);
        panelBusPais.setVisible(false);
        jtexBusPais.setVisible(false);
        panelBusProvincia.setVisible(false);
        jtexBusProvincia.setVisible(false);
        panelXPais.setVisible(false);
        panelXProvincia.setVisible(false);
        panelMosCiudadesHabilitadas.setVisible(true);
        panelMosCiudadesDeshabilitadas.setVisible(false);
        jScrollPane3.setVisible(false);
        labelInfo.setText("");
        labeCiudad.setText("");
        panelCerrar.setVisible(false);
    }//GEN-LAST:event_labelCerrarMouseClicked

    private void labelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseEntered
        // TODO add your handling code here:
        panelCerrar.setBackground(new Color(103,71,48));
        labelCerrar.setForeground(Color.white);
    }//GEN-LAST:event_labelCerrarMouseEntered

    private void labelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSalirMouseClicked
        // TODO add your handling code here:
        panelPrincipal.setVisible(false);
    }//GEN-LAST:event_labelSalirMouseClicked

    private void labelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSalirMouseEntered
        // TODO add your handling code here:
        panelSalir.setBackground(new Color(103,71,48));
        labelSalir.setForeground(Color.white);
    }//GEN-LAST:event_labelSalirMouseEntered

    private void labelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSalirMouseExited
        // TODO add your handling code here:
        panelSalir.setBackground(new Color(244,231,187));
        labelSalir.setForeground(Color.black);
    }//GEN-LAST:event_labelSalirMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtexBusPais;
    private javax.swing.JTextField jtexBusProvincia;
    private javax.swing.JTextField jtexCiudad;
    private javax.swing.JTextField jtexPais;
    private javax.swing.JTextField jtexProvincia;
    private javax.swing.JLabel labeCiudad;
    private javax.swing.JLabel labelBusPais;
    private javax.swing.JLabel labelBusProvincia;
    private javax.swing.JLabel labelCerrar;
    private javax.swing.JLabel labelEliminar;
    private javax.swing.JLabel labelGuardar;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelModificar;
    private javax.swing.JLabel labelMosCiudadesDeshabilitadas;
    private javax.swing.JLabel labelMosCiudadesHabilitadas;
    private javax.swing.JLabel labelNuevo;
    private javax.swing.JLabel labelSalir;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelXPais;
    private javax.swing.JLabel labelXProvincia;
    private javax.swing.JList<Ciudad> listCiudades;
    private javax.swing.JList<Ciudad> listaDeshabilitadas;
    private javax.swing.JPanel panelBusPais;
    private javax.swing.JPanel panelBusProvincia;
    private javax.swing.JPanel panelCerrar;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelGuardar;
    private javax.swing.JPanel panelModificar;
    private javax.swing.JPanel panelMosCiudadesDeshabilitadas;
    private javax.swing.JPanel panelMosCiudadesHabilitadas;
    private javax.swing.JPanel panelNuevo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JPanel panelXPais;
    private javax.swing.JPanel panelXProvincia;
    // End of variables declaration//GEN-END:variables
 //metodo para cargar la lista de ciudades habilitadas
    public DefaultListModel cargarCiudades() {

        listCiudades.setModel(modeloHabi);
        for (Ciudad carg : cd.obtenerCiudadHabilitada()) {
            modeloHabi.addElement(carg);
        }
        return modeloHabi;
    }
    //metodo para cargar la ciudades deshabilitadas
    public DefaultListModel cargarCiudadesDeshabilitadas() {

        listaDeshabilitadas.setModel(modeloDesah);
        for (Ciudad carg : cd.obtenerCiudadDesabilitada()) {
            modeloDesah.addElement(carg);
        }
        return modeloDesah;
    }

    public void desabilitaButton() {
        panelEliminar.setVisible(false);
        labelEliminar.setVisible(false);
        panelModificar.setVisible(false);
        labelModificar.setVisible(false);
        panelXPais.setVisible(false);
        labelXPais.setVisible(false);
        panelXProvincia.setVisible(false);
        labelXProvincia.setVisible(false);
    }

    public void desabilitarTexField() {
        jtexBusPais.setVisible(false);
        jtexBusProvincia.setVisible(false);
        panelXPais.setVisible(false);
        panelXProvincia.setVisible(false);
        labelXPais.setVisible(false);
        labelXProvincia.setVisible(false);
    }

    public void limpiarPais() {
        if (jtexPais.getText().equals("Ingrese un Pais")) {
            jtexPais.setText("");
            jtexPais.setForeground(Color.black);
        }
        if (String.valueOf(jtexProvincia.getText()).isEmpty()) {
            jtexProvincia.setText("Ingrese una Provincia");
            jtexProvincia.setForeground(Color.gray);
        }
        if (String.valueOf(jtexCiudad.getText()).isEmpty()) {
            jtexCiudad.setText("Ingrese una Ciudad");
            jtexCiudad.setForeground(Color.gray);
        }
    }

    public void limpiarProvincia() {
        if (jtexProvincia.getText().equals("Ingrese una Provincia")) {
            jtexProvincia.setText("");
            jtexProvincia.setForeground(Color.black);
        }
        if (String.valueOf(jtexPais.getText()).isEmpty()) {
            jtexPais.setText("Ingrese un Pais");
            jtexPais.setForeground(Color.gray);
        }
        if (String.valueOf(jtexCiudad.getText()).isEmpty()) {
            jtexCiudad.setText("Ingrese una Ciudad");
            jtexCiudad.setForeground(Color.gray);
        }
    }

    public void limpiarCiudad() {
        if (jtexCiudad.getText().equals("Ingrese una Ciudad")) {
            jtexCiudad.setText("");
            jtexCiudad.setForeground(Color.black);
        }
        if (String.valueOf(jtexProvincia.getText()).isEmpty()) {
            jtexProvincia.setText("Ingrese una Provincia");
            jtexProvincia.setForeground(Color.gray);
        }
        if (String.valueOf(jtexPais.getText()).isEmpty()) {
            jtexPais.setText("Ingrese un Pais");
            jtexPais.setForeground(Color.gray);
        }
    }

    public void cerrarBusqueda() {
        jScrollPane1.setVisible(false);
        panelBusPais.setVisible(false);
        jtexBusPais.setVisible(false);
        panelBusProvincia.setVisible(false);
        jtexBusProvincia.setVisible(false);
        panelXPais.setVisible(false);
        panelXProvincia.setVisible(false);
        panelMosCiudadesHabilitadas.setVisible(true);
        panelMosCiudadesDeshabilitadas.setVisible(false);
    }

    

    public void refrescarTablas() {
        modeloDesah.removeAllElements();
        cargarCiudadesDeshabilitadas();
        modeloHabi.removeAllElements();
        cargarCiudades();
    }
    public void limpiarTodo(){
          jtexProvincia.setText("");
        jtexCiudad.setText("");
        jtexPais.setText("");
        limpiarCiudad();
        limpiarProvincia();
        limpiarPais();
        jtexPais.setText("Ingrese un Pais");
        jtexPais.setForeground(Color.gray);
        panelGuardar.setVisible(true);
        labelGuardar.setVisible(true);
        panelEliminar.setVisible(false);
        labelEliminar.setVisible(false);
        panelModificar.setVisible(false);
        labelModificar.setVisible(false);
    }
       public String convierteMayuscula(String texto) {
        String[] palabras = texto.split(" ");  // Dividir el texto en palabras usando el espacio como separador
        StringBuilder nombreFormateado = new StringBuilder();
        for (String palabra : palabras) {
            if (!palabra.isEmpty()) {
                String primeraLetra = palabra.substring(0, 1).toUpperCase();
                String restoPalabra = palabra.substring(1).toLowerCase();
                nombreFormateado.append(primeraLetra).append(restoPalabra).append(" ");
            }
        }
        String nombreFinal = nombreFormateado.toString().trim();
        return nombreFinal;
    }
}
